package by.epam.bean;

public abstract class Appliance {

    abstract public int getCost();
    abstract public void setCost(int cost);
    abstract public int getPowerConsumption();
    abstract public void setPowerConsumption(int powerConsumption);
    abstract public double getWeight();
    abstract public void setWeight(double weight);
    abstract public double getCapacity();
    abstract public void setCapacity(double capacity);
    abstract public double getDepth();
    abstract public void setDepth(double depth);
    abstract public double getHeight();
    abstract public void setHeight(double height);
    abstract public double getWidth();
    abstract public void setWidth(double width);
    abstract public double getBatteryCapacity();
    abstract public void setBatteryCapacity(double batteryCapacity);
    abstract public String getOs();
    abstract public void setOs(String os);
    abstract public int getMemoryRom();
    abstract public void setMemoryRom(int memoryRom);
    abstract public int getSystemMemory();
    abstract public void setSystemMemory(int systemMemory);
    abstract public double getCpu();
    abstract public void setCpu(double cpu);
    abstract public int getDisplayInchs();
    abstract public void setDisplayInchs(int displayInchs);
    abstract public int getFreezerCapacity();
    abstract public void setFreezerCapacity(int freezerCapacity);
    abstract public double getOverallCapacity();
    abstract public void setOverallCapacity(double overallCapacity);
    abstract public int getNumberOfSpeakers();
    abstract public void setNumberOfSpeakers(int numberOfSpeakers);
    abstract public String getFrequencyRange();
    abstract public void setFrequencyRange(String frequencyRange);
    abstract public int getCordLength();
    abstract public void setCordLength(int cordLength);
    abstract public int getDisplayInches();
    abstract public void setDisplayInches(int displayInches);
    abstract public int getFlashMemoryCapacity();
    abstract public void setFlashMemoryCapacity(int flashMemoryCapacity);
    abstract public String getFilterType();
    abstract public void setFilterType(String filterType);
    abstract public String getBagType();
    abstract public void setBagType(String bagType);
    abstract public String getWandType();
    abstract public void setWandType(String wandType);
    abstract public int getMotorSpeedRegulation();
    abstract public void setMotorSpeedRegulation(int motorSpeedRegulation);
    abstract public int getCleaningWidth();
    abstract public void setCleaningWidth(int cleaningWidth);
    abstract public String getColor();
    abstract public void setColor(String color);
}
